### ISSUE TITLE
Análisis Exploratório Finanzas y Riesgo Crediticio

### ISSUE THREAD

**Issue by natalyamn** [ITACADEMYprojectes/ProjecteData#36]

**Comment by PauFernandezRipolles** [comment]
1. Realizamos el análisis de las dos variables que entran en juego en la pregunta del primer Sprint.
    Empezamos con el EDA y decidimos realizarlo cada uno por su lado para luego ponerlo en común y decidir la 
    estrategia a seguir conjuntamente.
2. Ponemos en común nuestros análisis exploratorios y hablamos de los outliers. Finalmente decidimos seguir la 
    estrategia que propone Natalya para realizar el análisis comparativo de las dos variables: categorizar la variable 
    balance para ver como varia el porcentaje de 
    incumplimiento de crédito en cada categoría. 
    Ante el problema de los numerosos outliers de balance , en parte mitigado por la categorización de la variable, 
    decidimos seguir en paralelo el análisis comparativo de las dos variables, uno lo realiza sin alterar la variable y otro 
    estandarizándola , así después podremos poner en común los resultados y sacar conclusiones.
